# Site
repository: boysbeanxious/boysbeanxious.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 한묘경
title: IT의 견고함에 비즈니스를 더한 future developer
email: bosbeanxious22@gmail.com
website: https://velog.io/@boysbeanxious

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  boysbeanxious
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: boysbeanxious
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs #![img](images/img13.png "img")
                  방송과 IT, 그리고 MBA 에서의 배움을 통해<br/>
                  감동을 전달하는 매개체로서의 미디어의 힘을 최대로 끌어내고자 하는, <br/>
                  미디어의 힘을 믿는, <br/>
                  데이터 분석가 한묘경입니다.
               <br/>
               <mark>관심분야</mark><br/>
               <i>#Data Analytics</i>, <i>#Machine Learning</i>, <i>#Media</i>, <i>#Platform</i><br/>
               <br/>
               <mark>Skill set</mark><br/>
                . Language : PYTHON, SQL, JAVA, shell script, jsp <br/>
                . Platform : WEB/APP<br/>
                . System   : Window, Linux<br/>
                . Tool     : IntelliJ, Eclips, jupyter notebook, DataGrip, Xplatform, GIT, SVN, Jenkins, Redmine, Jira<br/>

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 신세계아이앤씨
#         link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 프로그래머
        caption: 2017.01.09 ~ 2021.12.31
        quote: >
        description: | # this will include new lines to allow paragraphs
            신세계 면세점 BO(Back Office) 개발, 시스템 운영 <br/>
            - 프로젝트 지원
                - 디지털 혁신 프로젝트(2021)
                    - AS-IS 업무 가이드 및 TO-BE 시스템 DB테이블 설계 참여
                - 고도화 프로잭트(2017)
                    - QA 지원 및 DB 이행 스크립트 검수 
            - 시스템 개선
                - 데이터 품질 관리
                    - 일 검증 배치 프로그램 작성하여 담당업무 테이블의 데이터 품질 관리
                    - 수수료 지급금액에 대한 이상치 감지하여 특이사항 발생 시 모니터링 기능 강화
                - 마감업무자동화
                    - 재고/원가 마감작업 자동화를 통해 업무 처리 시간 75% 단축(8시간→ 2시간)
                    - One-step 마감업무를 step-by-step으로 변경하여 업무 리스크 경감
                - 모바일 체크인 기능 설계
                    - 구매전환율 내 허수를 줄이기 위해 모바일 체크인 기능 설계
                    - 개선 후 구매전환율 정확도 50%향상     
                    - 일자 별 이력 관리 구조를 통한 속도 이슈 개선
                - devops 테스트베드 구축
                    - 운영환경과 동일한 통합테스트 환경을 구축하여 팀 내 생산성 향상에 기여
                    - 수동으로 소스코드를 반영하는 기존 방식에서 벗어나 자동으로  반영되는 프로그램 개발
 #           . 2021.  면세점 Digital Transformation 프로젝트 오픈 지원<br/>   
 #                    수수료, 정산 시스템 개발, 운영<br/>   
 #           . 2020.  면세점 Digital Transformation 프로젝트 지원<br/>   
 #           . 2019.  대량구매 시스템 개발, 운영<br/>   
 #           . 2018.  물류시스템 개발, 운영<br/>   
 #           . 2017.  기준정보, 발주 시스템 개발, 운영<br/>   
            
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: RFM을 통한 술담화 고객 클러스터링
        caption: 2022.06 - 2022.07
        sub_title: <i>#SQL</i> , <i>#PYTHON</i> 
#         quote: >
        description: | # this will include new lines to allow paragraphs
            - 찾아오는 인생술, [술담화] 의 매출데이터로 고객 RFM 산출
            - RFM기반으로 클러스터링을 진행
            - 실루엣계수가 가장 높은 최적의 클러스터 개수 선택하여 고객 세분화

            
      - layout: left
        title: INSERT COIN<br/> Trilogy
        caption: 2020.10 - on going
        sub_title: <i>#Postgresql</i> , <i>#PYTHON</i> 
        quote: >
        description: | # this will include new lines to allow paragraphs
            - INSERT COIN I
                - 데이콘에서 진행한 [2021 금융데이터 활용경진대회]에 참여하여 주식 종료가격 예측 
                - 코로나 이후 하락장이라는 가설 설정과 AR모형을 통해 오차 최소화
                - 최종등수 15등으로 본선진출 
             - INSERT COIN II
                - 거시 지표 기반의 환율 예측 진행
                - 계량경제학을 통해 가격의 비정상성을 이해하고 증감율 기반으로 예측
                - 환율 이외의 GDP성장률, 유가 증감률과 같은 거시 지표 활용
                - 시계열 데이터로 선형회귀 수행
             - INSERT COIN III
                - 앞서 배운 내용을 기반으로 KOSPI/S&P500지수 예측 
                - 차분을 통해 계산된 증감률 기술지표와 거시지표를 feature로 활용
                - 예측이 아닌 상승과 하락의 분류로 변경하여 진행
                - 높은 정확도를 위한 최적 모델 탐색
      - layout: left
        title: 외식업 상권분석 및 업종 추천
        caption: 2022.04 - 2022.06
        sub_title: <i>#Postgresql</i> , <i>#PYTHON</i> 
        quote: >
        description: | # this will include new lines to allow paragraphs
            - 업종 별 매출에 영향을 미치는 요인 추출
            - 카이스트 주변과 유사한 상권 확인을 위한 군집 분석 진행 
            - 업종별 유의미한 변수 기반으로 카이스트 주변 상권의 예상 매출 top4 확인
            - 예상을 깨고 치킨전문점이 아닌 한식전문점이 가장 높은 매출을 보임  
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: KAIST
        caption: 2022.01 - 2023.02
        sub_title: 정보미디어 MBA
#         quote: >
#           Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          * 마케팅, 전략, 재무 등의 일반 경영관리에 대한 이해를 바탕으로 Business Analytics에 대한 힘을 기르기 위해 KAIST 정보미디어MBA에 입학
          * 데이터를 기반으로 비즈니스의 문제를 해결하는 인사이트를 얻기 위해 BA 집중분야를 이수
      - layout: left
        title: 성신여자대학교
        caption: 2011.03 - 2016.08
        sub_title: IT학부
#         quote: >
#           Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          * 정보미디어를 주전공으로 소프트웨어 공학을 기반 서비스 라이프 사이클 이해 및 요구사항 분석과 설계에 대해 심도 있게 학습<br/>
          * 컴퓨터 소프트웨어를 부전공으로 선택하여 컴퓨터 언어와 구조에 대한 이해를 기반으로 개발 프로젝트 진행<br/>
          * 졸업 프로젝트인 '매일매일 움직움직' 프로젝트의 기획과 개발에 참여하여 교내 경진대회 대상수상
          
        
  - title: Portfolio
    layout: text
    content: | # this will include new lines to allow paragraphs [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg) /![portfolio](images/portfolio.png "portfolio")
      지금까지 진행한 프로젝트의 포트폴리오입니다
      <iframe src="https://onedrive.live.com/embed?cid=8162585282E39357&resid=8162585282E39357%21126&authkey=AByv7wiF5g-d7v8&em=2" width="1208" height="720" frameborder="0" scrolling="no"></iframe>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
